name: github-rest
version: 1.1.2
verbatim:
  cabal-version: '>= 1.10'
license: BSD3
license-file: LICENSE
author:
  - Brandon Chinn <brandon@leapyear.io>
maintainer:
  - Brandon Chinn <brandon@leapyear.io>
category: GitHub
synopsis: Query the GitHub REST API programmatically
description: |
  Query the GitHub REST API programmatically, which can provide a more
  flexible and clear interface than if all of the endpoints and their types
  were defined as Haskell values.
extra-source-files:
  - README.md
  - CHANGELOG.md
  - test/**/*.golden

github: LeapYear/github-rest

ghc-options: -Wall
when:
  - condition: impl(ghc >= 8.0)
    ghc-options:
      - -Wcompat
      - -Wincomplete-record-updates
      - -Wincomplete-uni-patterns
      - -Wnoncanonical-monad-instances
  - condition: impl(ghc < 8.8)
    ghc-options:
      - -Wnoncanonical-monadfail-instances

dependencies:
- aeson >= 1.1.2.0 && < 2.1
- base >= 4.9 && < 5
- bytestring >= 0.10.8.1 && < 0.12
- http-client >= 0.5.13.1 && < 0.8
- http-client-tls >= 0.3.5.3 && < 0.4
- http-types >= 0.12.1 && < 0.13
- jwt >= 0.9.0 && < 0.12
- mtl >= 2.2.2 && < 2.3
- scientific >= 0.3.6.2 && < 0.4
- text >= 1.2.2.2 && < 1.3
- time >= 1.8.0.2 && < 1.12
- transformers >= 0.5.2.0 && < 0.6
- unliftio >= 0.2.7.0 && < 0.3
- unliftio-core >= 0.1.1.0 && < 0.3

library:
  source-dirs: src

tests:
  github-rest-test:
    source-dirs:  test
    main:         Main.hs
    dependencies:
    - aeson-qq
    - github-rest
    - tasty
    - tasty-golden
    - tasty-hunit
    - tasty-quickcheck
